################################################################################
# monitoring · dev overrides
################################################################################

loki:
  retentionPeriod: "168h"   # 7일

grafana:
  persistence:
    size: 500Mi
